version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: christiankm01/kilo:latest
    steps:
      - checkout
      - run: npm
workflows:
  builds:
    jobs:
      - build
  test:
    jobs:
      - build
